# Generated by Django 4.2.30 on 2026-08-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-featured', 'category', 'order', '-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('data_analysis', 'Data Analysis'), ('machine_learning', 'Machine Learning'), ('deep_learning', 'Deep Learning'), ('ai_agent', 'AI Agent'), ('web_development', 'Web Development'), ('environmental', 'Environmental Project')], default='web_development', max_length=50),
        ),
    ]
