# Generated by Django 4.2.30 on 2026-08-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_options_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('volunteer', 'Volunteer'), ('employed', 'Employed'), ('field_training', 'Field Training')], default='employed', max_length=30),
        ),
    ]
