# Generated by Django 4.2.30 on 2026-08-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_experience_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='category',
            field=models.CharField(choices=[('education', 'Education'), ('certificates', 'Certificates'), ('event', 'Event')], default='education', max_length=20),
        ),
    ]
