# Generated by Django 4.2.30 on 2026-08-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_education_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('data_science', 'Data Science'), ('ml_ai', 'Machine Learning & AI'), ('web_development', 'Web Development'), ('databases', 'Databases'), ('tools_platforms', 'Tools & Platforms'), ('cloud', 'Cloud'), ('social', 'Social')], max_length=20),
        ),
    ]
