# Generated by Django 4.2.30 on 2026-08-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_profile_twitter_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='about_bio',
            field=models.TextField(blank=True, help_text='Bio text displayed in the about section'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_bio',
            field=models.TextField(blank=True, help_text='Bio text displayed in the hero section'),
        ),
    ]
