# Generated by Django 4.2.30 on 2026-08-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_profile_bio_profile_about_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='competition_provider',
            field=models.CharField(blank=True, choices=[('zindi', 'Zindi'), ('kaggle', 'Kaggle'), ('driven_data', 'Driven Data'), ('other', 'Other')], help_text='Provider for Competitions & Hackathons category', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('data_analysis', 'Data Analysis'), ('machine_learning', 'Machine Learning'), ('deep_learning', 'Deep Learning'), ('ai_agent', 'AI Agent'), ('web_development', 'Web Development'), ('competitions', 'Competitions & Hackathons'), ('environmental', 'Environmental Project')], default='web_development', max_length=50),
        ),
    ]
